### PR TITLE
Add `yarn serve` via `serve` dependecy + script in package.json

### PR DESCRIPTION
**Pull request by svub**
add `serve` devDep
building i18n dicts
serve -p 8000

### CODE REVIEW

**Review by sisou — APPROVED** [review]
The only concern I have is that it adds a huge load of dependencies. Maybe we can either find a simpler server package with less cruft, or build a simple nodejs server script that serves the current folder.

**Comment by svub** [comment]
`serve` is just a devDep, should be no problem.

**Comment by hst-m** [comment]
that is a lot of dependencies to serve a couple files, just write a small node script

**Comment by hst-m** [comment]
I am counting 37 new external libraries in your PR for what, to do what Node.js can do in a couple lines of code?

**Comment by svub** [comment]
Feel free to add the Node.js script.

**Review by danimoh — CHANGES_REQUESTED** [review]
I also think a simple node script would be preferable.
Also the instructions in the Readme should be updated then.

**Comment by sisou** [comment]
I created https://github.com/nimiq/keyguard/pull/411 that adds a basic static server NodeJS script. Please check it out. I tested it, it works the same.

**Pull request closed without merging**
